#!/bin/bash

#ffmpeg -i /home/shasten/Wallpapers/sky2.jpg test.mp4
ffmpeg -video_size 1920x1080 -framerate 25 -f x11grab -i :0.0+0,0 -f alsa -ac 2 -i pulse -acodec aac -strict experimental xmonad1.mp4 && ecasound -i alsahw,4,0 -o xmonad1.wav
